//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarouselImage
    {
        public int CarouselImage_ID { get; set; }
        public int Blob_FK { get; set; }
        public string CarouselImage_Name { get; set; }
    
        public virtual Blob Blob { get; set; }
    }
}
