//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandProduct
    {
        public int CommandProduct_ID { get; set; }
        public int Command_FK { get; set; }
        public int Product_FK { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string xmlData { get; set; }
        public decimal ProductPrice { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Product Product { get; set; }
    }
}
