//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Command()
        {
            this.CommandProduct_Set = new HashSet<CommandProduct>();
            this.Command_History_Set = new HashSet<Command_History>();
            this.Command_Document_Set = new HashSet<Command_Document>();
            this.CommandAddress_Set = new HashSet<CommandAddress>();
        }
    
        public int Command_ID { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Command_Status Command_Status { get; set; }
        public int Customer_User_FK { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public Nullable<decimal> OptionShipmentCharge { get; set; }
        public Nullable<OptionShipmentType> OptionShipmentSecureType { get; set; }
        public Nullable<ShipmentType> ShipmentType { get; set; }
        public string xmlData { get; set; }
    
        public virtual Customer_User Customer_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommandProduct> CommandProduct_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Command_History> Command_History_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Command_Document> Command_Document_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommandAddress> CommandAddress_Set { get; set; }
    }
}
