//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command_Document
    {
        public int Document_FK { get; set; }
        public int Command_FK { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Document Document { get; set; }
    }
}
