//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandAddress
    {
        public CommanAddress_Type Type { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Address_FK { get; set; }
        public int Command_FK { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Address Address { get; set; }
    }
}
