//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    
    public enum Customer_User_Status : int
    {
        Disabled = -200,
        Creation = 0,
        Awaiting_MailConfirmation = 100,
        Active = 200,
        CommandWithoutSubscription = -180
    }
}
