//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public int Customer_User_FK { get; set; }
        public int Address_FK { get; set; }
        public Nullable<CustomerAddress_Type> Type { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Customer_User Customer_User { get; set; }
    }
}
