//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design_Config
    {
        public int Design_Config_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Design_Config_Status Status { get; set; }
        public string xmlData { get; set; }
        public Nullable<System.DateTime> CreationDatetime { get; set; }
        public Nullable<System.DateTime> LastUpdateDatetime { get; set; }
    }
}
