//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etiquette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etiquette()
        {
            this.Category_Set = new HashSet<Category>();
        }
    
        public int Etiquette_ID { get; set; }
        public int Blob_FK { get; set; }
        public string Etiquette_Name { get; set; }
    
        public virtual Blob Blob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Category_Set { get; set; }
    }
}
