//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MesJolisCotillonsEntities : DbContext
    {
        public MesJolisCotillonsEntities()
            : base("name=MesJolisCotillonsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Admin_User> Admin_User { get; set; }
        public virtual DbSet<Blob> Blobs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Command> Commands { get; set; }
        public virtual DbSet<CommandProduct> CommandProducts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer_User> Customer_User { get; set; }
        public virtual DbSet<Design_Config> Design_Config { get; set; }
        public virtual DbSet<Etiquette> Etiquettes { get; set; }
        public virtual DbSet<KeyWord> KeyWords { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Command_History> Command_History { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Command_Document> Command_Document { get; set; }
        public virtual DbSet<CommandAddress> CommandAddresses { get; set; }
        public virtual DbSet<CarouselImage> CarouselImages { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<LaPosteColissimo> LaPosteColissimoes { get; set; }
    }
}
