//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesJolisCotillons.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_fr_FR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MesJolisCotillons.Resources.Messages.Messages-fr-FR", typeof(Messages_fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une ou des catégories soumises n&apos;existent pas..
        /// </summary>
        internal static string CategoriesDoNotExist {
            get {
                return ResourceManager.GetString("CategoriesDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le produit &apos;{0}&apos; a été créé avec succès..
        /// </summary>
        internal static string CreateProductSuccess {
            get {
                return ResourceManager.GetString("CreateProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;opération `{0}` a été executée avec succès..
        /// </summary>
        internal static string DefaultReponseSuccess {
            get {
                return ResourceManager.GetString("DefaultReponseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le produit &apos;{0}&apos; a été supprimé avec succès..
        /// </summary>
        internal static string DeleteProductSuccess {
            get {
                return ResourceManager.GetString("DeleteProductSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les paramètres de Page doivent être supérieurs à 0..
        /// </summary>
        internal static string PageParametersNotGreaterThanZero {
            get {
                return ResourceManager.GetString("PageParametersNotGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots de passes ne sont pas identiques.
        /// </summary>
        internal static string PasswordAreNotSame {
            get {
                return ResourceManager.GetString("PasswordAreNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les mots de passes doivent avoir au moins {0} caractères.
        /// </summary>
        internal static string PasswordIsNotLongEnough {
            get {
                return ResourceManager.GetString("PasswordIsNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez remplir les champs requis.
        /// </summary>
        internal static string PleaseFillRequiredFieldsForm {
            get {
                return ResourceManager.GetString("PleaseFillRequiredFieldsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le produit avec l&apos;identifiant `{0}` n&apos;existe pas..
        /// </summary>
        internal static string ProductDoesNotExist {
            get {
                return ResourceManager.GetString("ProductDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur avec le mail `{0}` existe déja.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
    }
}
